server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/bjj
    username: bjj
    password: bjjpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        default_schema: bjj   # usa o schema criado no init

  sql:
    init:
      mode: always
      encoding: UTF-8

  security:
    oauth2:
      resourceserver:
        jwt:
          ##issuer-uri: http://keycloak:8080/realms/bjj
          ##para docker
          jwk-set-uri: http://keycloak:8080/realms/bjj/protocol/openid-connect/certs

# (opcional) logs de seguran√ßa pra debug:
  logging:
    level:
      org.springframework.security: DEBUG
