version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres-bjj
    environment:
      POSTGRES_DB: bjj
      POSTGRES_USER: bjj
      POSTGRES_PASSWORD: bjjpass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak-bjj
    command: ["start-dev", "--import-realm"]
    ports:
      - "8081:8080"
    environment:
      # forma "cl√°ssica" 
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      # forma nova (Keycloak Quarkus)
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

    volumes:
      - ./keycloak-import:/opt/keycloak/data/import
      - keycloak_data:/opt/keycloak/data
    restart: unless-stopped

  backend:
    build:
      context: ./bjjBackSpring
      dockerfile: Dockerfile
    container_name: bjj-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8090
    ports:
      - "8090:8090"
    depends_on:
      - postgres
      - keycloak
    restart: unless-stopped

  frontend:
    build:
      context: ./bjj-school
      dockerfile: Dockerfile
    container_name: bjj-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pg_data:
  keycloak_data:
